### ISSUE TITLE
Add Caption Editor

### ISSUE THREAD

**Issue by Adesii** [Adesii/Adesi-Alyx-ToolBox#9]
# Description of the Feature:
Now that we know how to make custom captions adding a caption editor is the next step after getting the basic sound events working.

## Todo:
- [x] basic editor window
- [ ] basic adding of captions
- [ ] basic removing of captions
- [x] basic view of already existing captions
- [x] include metadata from sound events
